version: "3.3"

services:
  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/gitlabrunner-admin
    command: >
      sh -c "npm run start"
    ports:
      - "3000:3000"
    container_name: admiin
